name = "url"
main = "src/index.ts"
compatibility_date = "2024-01-29"
node_compat = true
send_metrics = false

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
TOKEN = "token"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "UrlKV"
id = "123123123123123123"
